{
 "title": "Hosted Metrics Graphite",
 "tags": [ "hosted-metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" },
   { "name": "environment", "query": "stats.*" }
  ]
 },
 "panels": [
  {
   "title": "GW render rates by statuscode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "groupByNodes(perSecond(tsdb-gw.stats.$environment.*.api.request.render*.status.*.counter32), 'sum', 6, 8)"
    }
   ]
  },
  {
   "title": "GW render error percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(sumSeries(keepLastValue(tsdb-gw.aggstats.$environment.api.request.render.status.5*.rate32, 10)), sum(keepLastValue(tsdb-gw.aggstats.$environment.api.request.render.status.*.rate32, 10)), 0), 'error-pct')"
    }
   ]
  },
  {
   "title": "GW render Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(tsdb-gw.stats.$environment.*.api.request.render.latency.median.gauge32), 'median')"
    },
    {
     "target": "alias(avg(tsdb-gw.stats.$environment.*.api.request.render.latency.p90.gauge32), 'p90')"
    },
    {
     "target": "alias(maxSeries(consolidateBy(tsdb-gw.stats.$environment.*.api.request.render.latency.max.gauge32, 'max')), 'max')"
    }
   ]
  },
  {
   "title": "Metrictank Render rates by statuscode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "groupByNodes(perSecond(metrictank.stats.$environment.*.api.request.render*.status.*.counter32), 'sum', 6, 8)"
    }
   ]
  },
  {
   "title": "Metrictank Render error percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(#B,#A),'error-pct')",
     "targetFull": "alias(asPercent(sum(perSecond(metrictank.stats.$environment.*.api.request.render*.status.5*.counter32)),sum(perSecond(metrictank.stats.$environment.*.api.request.render*.status.*.counter32))),'error-pct')"
    }
   ]
  },
  {
   "title": "Metrictank render latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(metrictank.stats.$environment.*.api.request.render*.latency.median.gauge32), 'median')"
    },
    {
     "target": "alias(averageSeries(metrictank.stats.$environment.*.api.request.render*.latency.p90.gauge32), 'p90')"
    },
    {
     "target": "alias(consolidateBy(maxSeries(metrictank.stats.$environment.*.api.request.render*.latency.max.gauge32), 'max'), 'max')"
    }
   ]
  },
  {
   "title": "Graphite Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.$environment.timers.view.graphite.metrics.views.find_view.*.count_ps), 'find')"
    },
    {
     "target": "alias(sumSeries(stats.$environment.timers.view.graphite.render.views.{renderView,new_f}.*.count_ps), 'render')"
    },
    {
     "target": "alias(sumSeries(stats.$environment.response.5[0-9][0-9]), 'errors')"
    }
   ]
  },
  {
   "title": "Graphite Render latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(groupByNode(stats.$environment.timers.view.graphite.render.views.{renderView,new_f}.*.mean, 8, 'max')), 'mean')"
    },
    {
     "target": "alias(avg(stats.$environment.timers.view.graphite.render.views.{renderView,new_f}.*.upper_90), 'p90')"
    },
    {
     "target": "alias(consolidateBy(maxSeries(stats.$environment.timers.view.graphite.render.views.{renderView,new_f}.*.upper), 'max'), 'max')"
    }
   ]
  },
  {
   "title": "Speculative Query Stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNodes(perSecond(metrictank.stats.$environment.*.api.cluster.speculative.*.counter32), 'sum', 7)"
    }
   ]
  },
  {
   "title": "Metrictank Points returned per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sum(applyByNode(metrictank.stats.$environment.*.api.request.render.points_returned.values.rate32, 3, 'multiplySeries(sumSeries(%.api.request.render.points_returned.values.rate32), averageSeries(%.api.request.render.points_returned.mean.gauge32))')), 'points returned per second')"
    }
   ]
  },
  {
   "title": "Metrictank Series Scanned per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sum(applyByNode(metrictank.stats.$environment.*.api.request.render.series.values.rate32, 3, 'multiplySeries(sumSeries(%.api.request.render.series.values.rate32), averageSeries(%.api.request.render.series.mean.gauge32))')), 'series scanned per second')"
    }
   ]
  }
 ]
}