name: "build"

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

env:
  PROD_REGISTRY: "us-docker.pkg.dev/grafanalabs-global/docker-graphite-mt-prod"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Generate docker tag and commit SHA
        run: |
          bash ./graphite/docker-tag.sh
          DOCKER_TAG=$(cat .docker_tag)
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
          echo "Docker tag: $DOCKER_TAG"

      - name: Build image
        run: make build

      - name: Test image
        run: bash graphite/test.sh

      - name: Push image
        uses: grafana/shared-workflows/actions/docker-build-push-image@34f27887c37cafe70d34af57dfc86b468a31b8c4 # docker-build-push-image/v0.3.3
        with:
          push: ${{ github.ref_name == 'master' }}
          registries: gar
          tags: |-
            ${{ env.DOCKER_TAG }}
            type=raw,value=latest,enable=${{ github.ref_name == 'master' }}
          gar-image: "graphite-mt"
          context: "."
          file: "./Dockerfile"
          gar-environment: "prod"
